### ISSUE TITLE
Updated mixed content module

### ISSUE THREAD

**Issue by hi-upchen** [greenpeace/gpea-planet8-child-theme#1]
Please refer to the current page styles: [Vso Sample Page](https://www.greenpeace.org/hongkong/%e7%b6%a0%e8%89%b2%e5%92%8c%e5%b9%b3%e6%9d%b1%e4%ba%9e%e5%88%86%e9%83%a8%e5%b9%b4%e5%a0%b12019_vso/)

## Make the number animated.
![截圖 2020-03-18 下午4 29 32](https://user-images.githubusercontent.com/58502423/76946643-52216d80-693f-11ea-8ff8-feb530fca72d.png)

Sample see [jQuery Animated Number Counter From Zero To Value - Javascript Animation ](https://codepen.io/shivasurya/pen/FatiB) 

### Requirements:

1. Only animate the numbers in the title
2. Add command as thousand separators for all the numbers
3. Should work for the number which embeds in a string. ex `There are 1,000 people`. The `1,000` should be animated. 
4. The number animates after the aos `fade-left` effect. That is `fade-left` first, then animate numbers.

## Support PC background and mobile background
Now the `GPEA | Mixed Content Row Details` module uses the same image on pc version and mobile version. We need to able upload two images, one for PC and one for mobile.

![截圖 2020-03-18 下午5 22 07](https://user-images.githubusercontent.com/58502423/76945122-138ab380-693d-11ea-91b0-2899d6f4c7f8.png)

### Requirements:

1. Add field `Optional PC background-image` and `Optional mobile background image (Leave blank to use the same image as background image )`
2. If a user only uploads the pc version, show the pc version image when it's mobile devices. 
3. If a user only uploads the mobile version, show nothing when it's in pc devices.
4. If a user uploads both versions, show the corresponding images on different devices.
5. Please center alignment with the images.
6. You can refer to the module `GPEA | Donation Basic Details`. That module already support pc/mobile image uploads.

**Comment by eahk** [comment]
# Support PC background and mobile background
## Backend
Add mobile image insert field
<img width="1347" alt="Screenshot 2020-04-08 at 18 17 07" src="https://user-images.githubusercontent.com/53209063/78773604-0efa6d80-79c6-11ea-94f1-c5ae769e6e10.png">

## Desktop
<img width="1371" alt="Screenshot 2020-04-08 at 18 16 22" src="https://user-images.githubusercontent.com/53209063/78773410-c6db4b00-79c5-11ea-8168-a9f50e23dd43.png">

## Mobile
<img width="370" alt="Screenshot 2020-04-08 at 18 16 45" src="https://user-images.githubusercontent.com/53209063/78773430-ccd12c00-79c5-11ea-9e86-e96e55e76cb0.png">

**Comment by eahk** [comment]
# Make the number animated
## Create another animate number field
<img width="1298" alt="Screenshot 2020-04-08 at 18 17 19" src="https://user-images.githubusercontent.com/53209063/78773666-2a657880-79c6-11ea-9e1c-b61a4e9f26a3.png">

User needs to input the number text in the animate field to have the auto increasing effect and it will also support adding comma as the thousand operators.

**Comment by hi-upchen** [comment]
Nice work.
