### ISSUE TITLE
Load fonts faster - NotoSans TC

### ISSUE THREAD

**Issue by eahk** [greenpeace/gpea-planet8-child-theme#13]
There is an enormous network payload detected when we evaluate the page speed of planet8 on [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgreenpeace.org%2Fhongkong)

The issue is that the site seems downloading the Noto Sans TC via .otf format and the size is super large.

![Screenshot 2020-03-31 at 10 06 49](https://user-images.githubusercontent.com/53209063/77979532-7b76cc00-7337-11ea-97d8-10e28639f12d.png)

Suggest to replace with Googe Font cdn 
[Noto Sans TC](https://fonts.google.com/specimen/Noto+Sans+TC)
[Noto Sans HK](https://fonts.google.com/specimen/Noto+Sans+HK)

Standard link stylesheet
```html
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+HK:400,700,900&display=swap&subset=chinese-hongkong" rel="stylesheet">
```
@Import
```css
@import url('https://fonts.googleapis.com/css?family=Noto+Sans+HK:400,700,900&display=swap&subset=chinese-hongkong');
```

**Comment by hi-upchen** [comment]
Resolved.
