### ISSUE TITLE
New Module: GPEA | iframe container

### ISSUE THREAD

**Issue by hi-upchen** [greenpeace/gpea-planet8-child-theme#7]
Actually this module is just a wrapper to make sure the iframe is as width as other components.

![editing_page](https://user-images.githubusercontent.com/58502423/77044183-ec45ec00-69f9-11ea-8311-6cb4da57fe0f.png)

### Requirements:

1. Support the `full-width` and `article-width` layout.
2. `article-width` layout is the default value.
3. Wrap the `script` content into a `ct-container` if the user choose `article-width` layout.

```
<section class="section-iframe-container">
    <div class="ct-container">
         ...
    </div>
</section>

```

4. If the user chooses `full-width` layout, just wrap it into a section (the default is 100% width). 

```
<section class="section-iframe-container">
         ...
</section>

```

5. Code highlight the textarea.

---

### Note:

* from Alessandro: 

```embedded video are surrounded by a div with class "embed-container", 
you can play with a parent class, in order to override the style of the iframe.

Ah no, it applies to oEmbed HTML, we used this : https://developer.wordpress.org/reference/hooks/embed_oembed_html/
```

**Comment by eahk** [comment]
```javascript```
import { debounce } from 'throttle-debounce';

export default function() {
  const fbVideos = document.querySelectorAll(
    'iframe[src^="https://www.facebook.com/"]'
  );

  function fixFbVideoHeights() {
    Array.from(fbVideos).forEach(function(video) {
      video.style.height = video.offsetWidth + 'px';
    });
  }

  fixFbVideoHeights();
  window.addEventListener('load', fixFbVideoHeights);
  window.addEventListener('resize', debounce(500, fixFbVideoHeights));
}
```

Weird javascript in `/frontend/js/components/facebook-video.js` to force facebook video iframe height.

**Comment by hi-upchen** [comment]
I met the weird white space under the FB video too. I think we can just remove this part since it looks fine without setting the iframe height here.
